### ISSUE TITLE
Non-typescript version?

### ISSUE THREAD

**Issue by robdodson** [Polymer/prpl-server-node#2]
Is the plant keep this project in typescript or will there also be a vanilla js version>?

**Comment by aomarks** [comment]
Up for discussion. As a reference server, it is appealing to have a pure JS implementation to look at here on the repo, since I imagine TS could be a turn off for some people. On the other hand, being in TS obviously doesn't preclude it from being used in a pure JS project, and the compiler will also produce perfectly readable JS preserving comments if you want to read the source that way.

What do you think @robdodson?

**Comment by robdodson** [comment]
I'd strongly advocate for a plain JS version. I think a lot of folks will see TypeScript and just bail early.

**Comment by rictic** [comment]
We could use `jsconfig.json` to get typescript's type checking of a pure JS project. Docs: https://code.visualstudio.com/docs/languages/jsconfig

**Comment by drwaky** [comment]
+1 for a plain JS version.

**Comment by justinfagnani** [comment]
The plain JS version is what we publish to npm.

Types help us tremendously, and I haven't seen them be a major barrier to adoption. In fact I've heard that they've helped new contributors understand the code even when they hadn't used TypeScript before.

Running the compiler is very easy and very fast. If someone thinks that this is preventing them from actual contributions they want to make, we can discuss options, but until then I'd like to close issue, as we've already standardized on TypeScript.

**Comment by justinfagnani** [comment]
@robdodson what do you mean by bail early? Users shouldn't​ even be able to tell it's TypeScript, other than maybe less runtime errors ;)

**Comment by robdodson** [comment]
I'm not sure if there was a readme published when I wrote that comment. I was thinking this was more of an Express boilerplate, instead of a module to be used inside of Express. If that's the case then I think consumers will care less about how it's implemented.

I do honestly think it runs the risk of limiting the audience of open source contributors but that's a decision left up to your team. Feel free to close.

**Comment by aomarks** [comment]
Thanks Rob! There was no readme when you posted :) We'll stick with TypeScript for now, but point taken about community contributions.
