### ISSUE TITLE
Clarification for AppEngine Free Tier

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/prpl-server-node#21]
The readme suggests there is a free-tier for AppEngine, which there is, but only for Standard. Node won't run on that though and requires AppEngine Flex which doesn't have a free tier and is quite expensive so the readme might be misleading:

> Google App Engine is a managed server platform that supports Node and has a free tier. You can deploy prpl-server to App Engine with a few steps:

**Comment by aomarks** [comment]
Removed the part about free tier. I was under the mistaken impression it applied to flex, but sadly you're right! Thanks for reporting.
