### ISSUE TITLE
Not seeing preload headers

### ISSUE THREAD

**Issue by arthurevans** [Polymer/prpl-server-node#38]
I'm seeing the "Detected push manifest" lines, but I don't see preload headers in the responses.
Shouldn't these headers show up in the network panel under "response headers" for the entrypoint?

**Comment by arthurevans** [comment]
I am seeing:

`<link rel=preload> must have a valid 'as' value` in the console, but I can't see any `link rel=preload` tags or headers.

There are a bunch of `link rel="prefetch"` tags showing up in index.html. But I think those are generated by the build (indeed, looking at the built file, that seems to be the case). 😕

**Comment by aomarks** [comment]
Talked offline. The headers were not on the expected document, so was a build problem, not a server problem.
