### ISSUE TITLE
Go version

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/prpl-server-node#40]
FYI: I created a Go version here: https://github.com/CaptainCodeman/prpl-server-go

There's still some spit and polish needed but it's working for me to run the Shop demo app (after adding `"basePath": true` to the build configs) plus a few other projects I'm working on.

It should be usable on AppEngine Standard so will qualify for the free-usage tier (vs node which requires Flex).

I'll look at adding HTTPS directly given Go's support for it.

**Comment by joeblew99** [comment]
@CaptainCodeman thanks for this. Really useful !! Was thinking about this myself
