### ISSUE TITLE
Upgrade Polymer/browser-capabilities to 0.2.2

### ISSUE THREAD

**Issue by paales** [Polymer/prpl-server-node#60]
Now has support for Chrome Headless: https://github.com/Polymer/browser-capabilities/blob/master/CHANGELOG.md

This way in combination with rendertron it will properly use the correct build.

**Comment by aomarks** [comment]
I don't think we need to bump the version explicitly. You should just be able to `npm update` to get the new dependency.

**Comment by paales** [comment]
Ohhh, right :D
